services:
  app:
    image: todo-front-dev
    attach: false
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-front-dev
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api/
  mongo:
    image: mongo
    attach: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    attach: false
    image: redis
    command:
      ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-back-dev
    #attach: false
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    #attach: false
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server